// generate_core_registry.js — Expands core_institutes.ndjson to 300+ entries
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '..', 'data', 'core', 'core_institutes.ndjson');

const institutes = [
  // ── IITs (all 23) ────────────────────────────────────────────────────────
  {canonicalName:"Indian Institute of Technology Madras",displayName:"IIT Madras",institutionType:"IIT",institutionFamily:"Engineering",state:"Tamil Nadu",city:"Chennai",website:"https://www.iitm.ac.in",established:1959,searchBoost:1.5,coreTier:1},
  {canonicalName:"Indian Institute of Technology Delhi",displayName:"IIT Delhi",institutionType:"IIT",institutionFamily:"Engineering",state:"Delhi",city:"New Delhi",website:"https://www.iitd.ac.in",established:1961,searchBoost:1.5,coreTier:1},
  {canonicalName:"Indian Institute of Technology Bombay",displayName:"IIT Bombay",institutionType:"IIT",institutionFamily:"Engineering",state:"Maharashtra",city:"Mumbai",website:"https://www.iitb.ac.in",established:1958,searchBoost:1.5,coreTier:1},
  {canonicalName:"Indian Institute of Technology Kanpur",displayName:"IIT Kanpur",institutionType:"IIT",institutionFamily:"Engineering",state:"Uttar Pradesh",city:"Kanpur",website:"https://www.iitk.ac.in",established:1959,searchBoost:1.5,coreTier:1},
  {canonicalName:"Indian Institute of Technology Kharagpur",displayName:"IIT Kharagpur",institutionType:"IIT",institutionFamily:"Engineering",state:"West Bengal",city:"Kharagpur",website:"https://www.iitkgp.ac.in",established:1951,searchBoost:1.5,coreTier:1},
  {canonicalName:"Indian Institute of Technology Roorkee",displayName:"IIT Roorkee",institutionType:"IIT",institutionFamily:"Engineering",state:"Uttarakhand",city:"Roorkee",website:"https://www.iitr.ac.in",established:1847,searchBoost:1.5,coreTier:1},
  {canonicalName:"Indian Institute of Technology Guwahati",displayName:"IIT Guwahati",institutionType:"IIT",institutionFamily:"Engineering",state:"Assam",city:"Guwahati",website:"https://www.iitg.ac.in",established:1994,searchBoost:1.5,coreTier:1},
  {canonicalName:"Indian Institute of Technology Hyderabad",displayName:"IIT Hyderabad",institutionType:"IIT",institutionFamily:"Engineering",state:"Telangana",city:"Hyderabad",website:"https://www.iith.ac.in",established:2008,searchBoost:1.4,coreTier:1},
  {canonicalName:"Indian Institute of Technology BHU",displayName:"IIT BHU",institutionType:"IIT",institutionFamily:"Engineering",state:"Uttar Pradesh",city:"Varanasi",website:"https://www.iitbhu.ac.in",established:1919,searchBoost:1.4,coreTier:1},
  {canonicalName:"Indian Institute of Technology Gandhinagar",displayName:"IIT Gandhinagar",institutionType:"IIT",institutionFamily:"Engineering",state:"Gujarat",city:"Gandhinagar",website:"https://www.iitgn.ac.in",established:2008,searchBoost:1.4,coreTier:1},
  {canonicalName:"Indian Institute of Technology Indore",displayName:"IIT Indore",institutionType:"IIT",institutionFamily:"Engineering",state:"Madhya Pradesh",city:"Indore",website:"https://www.iiti.ac.in",established:2009,searchBoost:1.4,coreTier:1},
  {canonicalName:"Indian Institute of Technology Bhubaneswar",displayName:"IIT Bhubaneswar",institutionType:"IIT",institutionFamily:"Engineering",state:"Odisha",city:"Bhubaneswar",website:"https://www.iitbbs.ac.in",established:2008,searchBoost:1.4,coreTier:1},
  {canonicalName:"Indian Institute of Technology Jodhpur",displayName:"IIT Jodhpur",institutionType:"IIT",institutionFamily:"Engineering",state:"Rajasthan",city:"Jodhpur",website:"https://www.iitj.ac.in",established:2008,searchBoost:1.4,coreTier:1},
  {canonicalName:"Indian Institute of Technology Ropar",displayName:"IIT Ropar",institutionType:"IIT",institutionFamily:"Engineering",state:"Punjab",city:"Ropar",website:"https://www.iitrpr.ac.in",established:2008,searchBoost:1.3,coreTier:1},
  {canonicalName:"Indian Institute of Technology Patna",displayName:"IIT Patna",institutionType:"IIT",institutionFamily:"Engineering",state:"Bihar",city:"Patna",website:"https://www.iitp.ac.in",established:2008,searchBoost:1.3,coreTier:1},
  {canonicalName:"Indian Institute of Technology Mandi",displayName:"IIT Mandi",institutionType:"IIT",institutionFamily:"Engineering",state:"Himachal Pradesh",city:"Mandi",website:"https://www.iitmandi.ac.in",established:2009,searchBoost:1.3,coreTier:1},
  {canonicalName:"Indian Institute of Technology Tirupati",displayName:"IIT Tirupati",institutionType:"IIT",institutionFamily:"Engineering",state:"Andhra Pradesh",city:"Tirupati",website:"https://www.iittp.ac.in",established:2015,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Technology Palakkad",displayName:"IIT Palakkad",institutionType:"IIT",institutionFamily:"Engineering",state:"Kerala",city:"Palakkad",website:"https://www.iitpkd.ac.in",established:2015,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Technology Dharwad",displayName:"IIT Dharwad",institutionType:"IIT",institutionFamily:"Engineering",state:"Karnataka",city:"Dharwad",website:"https://www.iitdh.ac.in",established:2015,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Technology Bhilai",displayName:"IIT Bhilai",institutionType:"IIT",institutionFamily:"Engineering",state:"Chhattisgarh",city:"Bhilai",website:"https://www.iitbhilai.ac.in",established:2016,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Technology Goa",displayName:"IIT Goa",institutionType:"IIT",institutionFamily:"Engineering",state:"Goa",city:"Goa",website:"https://www.iitgoa.ac.in",established:2016,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Technology Jammu",displayName:"IIT Jammu",institutionType:"IIT",institutionFamily:"Engineering",state:"Jammu and Kashmir",city:"Jammu",website:"https://www.iitjammu.ac.in",established:2016,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Technology Dhanbad",displayName:"IIT (ISM) Dhanbad",institutionType:"IIT",institutionFamily:"Engineering",state:"Jharkhand",city:"Dhanbad",website:"https://www.iitism.ac.in",established:1926,searchBoost:1.3,coreTier:1},

  // ── IIMs (all 20) ─────────────────────────────────────────────────────────
  {canonicalName:"Indian Institute of Management Ahmedabad",displayName:"IIM Ahmedabad",institutionType:"IIM",institutionFamily:"Management",state:"Gujarat",city:"Ahmedabad",website:"https://www.iima.ac.in",established:1961,searchBoost:1.5,coreTier:1},
  {canonicalName:"Indian Institute of Management Bangalore",displayName:"IIM Bangalore",institutionType:"IIM",institutionFamily:"Management",state:"Karnataka",city:"Bangalore",website:"https://www.iimb.ac.in",established:1973,searchBoost:1.5,coreTier:1},
  {canonicalName:"Indian Institute of Management Calcutta",displayName:"IIM Calcutta",institutionType:"IIM",institutionFamily:"Management",state:"West Bengal",city:"Kolkata",website:"https://www.iimcal.ac.in",established:1961,searchBoost:1.5,coreTier:1},
  {canonicalName:"Indian Institute of Management Lucknow",displayName:"IIM Lucknow",institutionType:"IIM",institutionFamily:"Management",state:"Uttar Pradesh",city:"Lucknow",website:"https://www.iiml.ac.in",established:1984,searchBoost:1.4,coreTier:1},
  {canonicalName:"Indian Institute of Management Kozhikode",displayName:"IIM Kozhikode",institutionType:"IIM",institutionFamily:"Management",state:"Kerala",city:"Kozhikode",website:"https://www.iimk.ac.in",established:1996,searchBoost:1.4,coreTier:1},
  {canonicalName:"Indian Institute of Management Indore",displayName:"IIM Indore",institutionType:"IIM",institutionFamily:"Management",state:"Madhya Pradesh",city:"Indore",website:"https://www.iimidr.ac.in",established:1996,searchBoost:1.4,coreTier:1},
  {canonicalName:"Indian Institute of Management Shillong",displayName:"IIM Shillong",institutionType:"IIM",institutionFamily:"Management",state:"Meghalaya",city:"Shillong",website:"https://www.iimshillong.ac.in",established:2007,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Management Rohtak",displayName:"IIM Rohtak",institutionType:"IIM",institutionFamily:"Management",state:"Haryana",city:"Rohtak",website:"https://www.iimrohtak.ac.in",established:2009,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Management Ranchi",displayName:"IIM Ranchi",institutionType:"IIM",institutionFamily:"Management",state:"Jharkhand",city:"Ranchi",website:"https://www.iimranchi.ac.in",established:2009,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Management Raipur",displayName:"IIM Raipur",institutionType:"IIM",institutionFamily:"Management",state:"Chhattisgarh",city:"Raipur",website:"https://www.iimraipur.ac.in",established:2010,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Management Tiruchirappalli",displayName:"IIM Trichy",institutionType:"IIM",institutionFamily:"Management",state:"Tamil Nadu",city:"Tiruchirappalli",website:"https://www.iimtrichy.ac.in",established:2011,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Management Kashipur",displayName:"IIM Kashipur",institutionType:"IIM",institutionFamily:"Management",state:"Uttarakhand",city:"Kashipur",website:"https://www.iimkashipur.ac.in",established:2011,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Management Udaipur",displayName:"IIM Udaipur",institutionType:"IIM",institutionFamily:"Management",state:"Rajasthan",city:"Udaipur",website:"https://www.iimu.ac.in",established:2011,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Management Nagpur",displayName:"IIM Nagpur",institutionType:"IIM",institutionFamily:"Management",state:"Maharashtra",city:"Nagpur",website:"https://www.iimnagpur.ac.in",established:2015,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Management Amritsar",displayName:"IIM Amritsar",institutionType:"IIM",institutionFamily:"Management",state:"Punjab",city:"Amritsar",website:"https://www.iimamritsar.ac.in",established:2015,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Management Bodh Gaya",displayName:"IIM Bodh Gaya",institutionType:"IIM",institutionFamily:"Management",state:"Bihar",city:"Bodh Gaya",website:"https://www.iimbg.ac.in",established:2015,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Management Sirmaur",displayName:"IIM Sirmaur",institutionType:"IIM",institutionFamily:"Management",state:"Himachal Pradesh",city:"Sirmaur",website:"https://www.iimsirmaur.ac.in",established:2015,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Management Sambalpur",displayName:"IIM Sambalpur",institutionType:"IIM",institutionFamily:"Management",state:"Odisha",city:"Sambalpur",website:"https://www.iimsambalpur.ac.in",established:2015,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Management Visakhapatnam",displayName:"IIM Visakhapatnam",institutionType:"IIM",institutionFamily:"Management",state:"Andhra Pradesh",city:"Visakhapatnam",website:"https://www.iimv.ac.in",established:2015,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Management Jammu",displayName:"IIM Jammu",institutionType:"IIM",institutionFamily:"Management",state:"Jammu and Kashmir",city:"Jammu",website:"https://www.iimj.ac.in",established:2016,searchBoost:1.1,coreTier:1},

  // ── NITs (all 31) ─────────────────────────────────────────────────────────
  {canonicalName:"National Institute of Technology Tiruchirappalli",displayName:"NIT Trichy",institutionType:"NIT",institutionFamily:"Engineering",state:"Tamil Nadu",city:"Tiruchirappalli",website:"https://www.nitt.edu",established:1964,searchBoost:1.4,coreTier:1},
  {canonicalName:"National Institute of Technology Karnataka Surathkal",displayName:"NIT Surathkal",institutionType:"NIT",institutionFamily:"Engineering",state:"Karnataka",city:"Surathkal",website:"https://www.nitk.ac.in",established:1960,searchBoost:1.4,coreTier:1},
  {canonicalName:"National Institute of Technology Rourkela",displayName:"NIT Rourkela",institutionType:"NIT",institutionFamily:"Engineering",state:"Odisha",city:"Rourkela",website:"https://www.nitrkl.ac.in",established:1961,searchBoost:1.3,coreTier:1},
  {canonicalName:"National Institute of Technology Warangal",displayName:"NIT Warangal",institutionType:"NIT",institutionFamily:"Engineering",state:"Telangana",city:"Warangal",website:"https://www.nitw.ac.in",established:1959,searchBoost:1.3,coreTier:1},
  {canonicalName:"National Institute of Technology Calicut",displayName:"NIT Calicut",institutionType:"NIT",institutionFamily:"Engineering",state:"Kerala",city:"Calicut",website:"https://www.nitc.ac.in",established:1961,searchBoost:1.3,coreTier:1},
  {canonicalName:"Motilal Nehru National Institute of Technology Allahabad",displayName:"MNNIT Allahabad",institutionType:"NIT",institutionFamily:"Engineering",state:"Uttar Pradesh",city:"Allahabad",website:"https://www.mnnit.ac.in",established:1961,searchBoost:1.3,coreTier:1},
  {canonicalName:"Malaviya National Institute of Technology Jaipur",displayName:"MNIT Jaipur",institutionType:"NIT",institutionFamily:"Engineering",state:"Rajasthan",city:"Jaipur",website:"https://www.mnit.ac.in",established:1963,searchBoost:1.2,coreTier:1},
  {canonicalName:"Visvesvaraya National Institute of Technology Nagpur",displayName:"VNIT Nagpur",institutionType:"NIT",institutionFamily:"Engineering",state:"Maharashtra",city:"Nagpur",website:"https://www.vnit.ac.in",established:1960,searchBoost:1.2,coreTier:1},
  {canonicalName:"Maulana Azad National Institute of Technology Bhopal",displayName:"MANIT Bhopal",institutionType:"NIT",institutionFamily:"Engineering",state:"Madhya Pradesh",city:"Bhopal",website:"https://www.manit.ac.in",established:1960,searchBoost:1.2,coreTier:1},
  {canonicalName:"National Institute of Technology Kurukshetra",displayName:"NIT Kurukshetra",institutionType:"NIT",institutionFamily:"Engineering",state:"Haryana",city:"Kurukshetra",website:"https://www.nitkkr.ac.in",established:1963,searchBoost:1.2,coreTier:1},
  {canonicalName:"National Institute of Technology Durgapur",displayName:"NIT Durgapur",institutionType:"NIT",institutionFamily:"Engineering",state:"West Bengal",city:"Durgapur",website:"https://www.nitdgp.ac.in",established:1960,searchBoost:1.2,coreTier:1},
  {canonicalName:"National Institute of Technology Silchar",displayName:"NIT Silchar",institutionType:"NIT",institutionFamily:"Engineering",state:"Assam",city:"Silchar",website:"https://www.nits.ac.in",established:1967,searchBoost:1.1,coreTier:1},
  {canonicalName:"National Institute of Technology Srinagar",displayName:"NIT Srinagar",institutionType:"NIT",institutionFamily:"Engineering",state:"Jammu and Kashmir",city:"Srinagar",website:"https://www.nitsri.ac.in",established:1960,searchBoost:1.1,coreTier:1},
  {canonicalName:"National Institute of Technology Hamirpur",displayName:"NIT Hamirpur",institutionType:"NIT",institutionFamily:"Engineering",state:"Himachal Pradesh",city:"Hamirpur",website:"https://www.nith.ac.in",established:1986,searchBoost:1.1,coreTier:1},
  {canonicalName:"National Institute of Technology Delhi",displayName:"NIT Delhi",institutionType:"NIT",institutionFamily:"Engineering",state:"Delhi",city:"New Delhi",website:"https://www.nitdelhi.ac.in",established:2010,searchBoost:1.1,coreTier:1},
  {canonicalName:"National Institute of Technology Goa",displayName:"NIT Goa",institutionType:"NIT",institutionFamily:"Engineering",state:"Goa",city:"Goa",website:"https://www.nitgoa.ac.in",established:2010,searchBoost:1.1,coreTier:1},
  {canonicalName:"National Institute of Technology Agartala",displayName:"NIT Agartala",institutionType:"NIT",institutionFamily:"Engineering",state:"Tripura",city:"Agartala",website:"https://www.nita.ac.in",established:1965,searchBoost:1.1,coreTier:1},
  {canonicalName:"National Institute of Technology Manipur",displayName:"NIT Manipur",institutionType:"NIT",institutionFamily:"Engineering",state:"Manipur",city:"Imphal",website:"https://www.nitmanipur.ac.in",established:2010,searchBoost:1.0,coreTier:1},
  {canonicalName:"National Institute of Technology Uttarakhand",displayName:"NIT Uttarakhand",institutionType:"NIT",institutionFamily:"Engineering",state:"Uttarakhand",city:"Srinagar",website:"https://www.nituk.ac.in",established:2009,searchBoost:1.0,coreTier:1},
  {canonicalName:"National Institute of Technology Puducherry",displayName:"NIT Puducherry",institutionType:"NIT",institutionFamily:"Engineering",state:"Puducherry",city:"Puducherry",website:"https://www.nitpy.ac.in",established:2010,searchBoost:1.0,coreTier:1},
  {canonicalName:"Sardar Vallabhbhai National Institute of Technology Surat",displayName:"SVNIT Surat",institutionType:"NIT",institutionFamily:"Engineering",state:"Gujarat",city:"Surat",website:"https://www.svnit.ac.in",established:1961,searchBoost:1.2,coreTier:1},
  {canonicalName:"National Institute of Technology Patna",displayName:"NIT Patna",institutionType:"NIT",institutionFamily:"Engineering",state:"Bihar",city:"Patna",website:"https://www.nitp.ac.in",established:1886,searchBoost:1.1,coreTier:1},
  {canonicalName:"National Institute of Technology Meghalaya",displayName:"NIT Meghalaya",institutionType:"NIT",institutionFamily:"Engineering",state:"Meghalaya",city:"Shillong",website:"https://www.nitm.ac.in",established:2010,searchBoost:1.0,coreTier:1},
  {canonicalName:"National Institute of Technology Sikkim",displayName:"NIT Sikkim",institutionType:"NIT",institutionFamily:"Engineering",state:"Sikkim",city:"Ravangla",website:"https://www.nitsikkim.ac.in",established:2010,searchBoost:1.0,coreTier:1},
  {canonicalName:"National Institute of Technology Mizoram",displayName:"NIT Mizoram",institutionType:"NIT",institutionFamily:"Engineering",state:"Mizoram",city:"Aizawl",website:"https://www.nitmz.ac.in",established:2010,searchBoost:1.0,coreTier:1},
  {canonicalName:"National Institute of Technology Arunachal Pradesh",displayName:"NIT Arunachal Pradesh",institutionType:"NIT",institutionFamily:"Engineering",state:"Arunachal Pradesh",city:"Yupia",website:"https://www.nitap.ac.in",established:2010,searchBoost:1.0,coreTier:1},
  {canonicalName:"National Institute of Technology Nagaland",displayName:"NIT Nagaland",institutionType:"NIT",institutionFamily:"Engineering",state:"Nagaland",city:"Chumukedima",website:"https://www.nitnagaland.ac.in",established:2010,searchBoost:1.0,coreTier:1},
  {canonicalName:"National Institute of Technology Andhra Pradesh",displayName:"NIT Andhra Pradesh",institutionType:"NIT",institutionFamily:"Engineering",state:"Andhra Pradesh",city:"Tadepalligudem",website:"https://www.nitandhra.ac.in",established:2015,searchBoost:1.0,coreTier:1},
  {canonicalName:"National Institute of Technology Jamshedpur",displayName:"NIT Jamshedpur",institutionType:"NIT",institutionFamily:"Engineering",state:"Jharkhand",city:"Jamshedpur",website:"https://www.nitjsr.ac.in",established:1960,searchBoost:1.2,coreTier:1},
  {canonicalName:"Dr. B.R. Ambedkar National Institute of Technology Jalandhar",displayName:"NIT Jalandhar",institutionType:"NIT",institutionFamily:"Engineering",state:"Punjab",city:"Jalandhar",website:"https://www.nitj.ac.in",established:1987,searchBoost:1.2,coreTier:1},
  {canonicalName:"National Institute of Technology Raipur",displayName:"NIT Raipur",institutionType:"NIT",institutionFamily:"Engineering",state:"Chhattisgarh",city:"Raipur",website:"https://www.nitrr.ac.in",established:1956,searchBoost:1.1,coreTier:1},

  // ── IIITs ────────────────────────────────────────────────────────────────
  {canonicalName:"Indian Institute of Information Technology Hyderabad",displayName:"IIIT Hyderabad",institutionType:"IIIT",institutionFamily:"Engineering",state:"Telangana",city:"Hyderabad",website:"https://www.iiit.ac.in",established:1998,searchBoost:1.4,coreTier:1},
  {canonicalName:"Indian Institute of Information Technology Allahabad",displayName:"IIIT Allahabad",institutionType:"IIIT",institutionFamily:"Engineering",state:"Uttar Pradesh",city:"Allahabad",website:"https://www.iiita.ac.in",established:1999,searchBoost:1.3,coreTier:1},
  {canonicalName:"International Institute of Information Technology Bangalore",displayName:"IIIT Bangalore",institutionType:"IIIT",institutionFamily:"Engineering",state:"Karnataka",city:"Bangalore",website:"https://www.iiitb.ac.in",established:1999,searchBoost:1.3,coreTier:1},
  {canonicalName:"Indraprastha Institute of Information Technology Delhi",displayName:"IIIT Delhi",institutionType:"IIIT",institutionFamily:"Engineering",state:"Delhi",city:"New Delhi",website:"https://www.iiitd.ac.in",established:2008,searchBoost:1.3,coreTier:1},
  {canonicalName:"Indian Institute of Information Technology Gwalior",displayName:"IIIT Gwalior",institutionType:"IIIT",institutionFamily:"Engineering",state:"Madhya Pradesh",city:"Gwalior",website:"https://www.iiitm.ac.in",established:1997,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Information Technology Jabalpur",displayName:"IIIT Jabalpur",institutionType:"IIIT",institutionFamily:"Engineering",state:"Madhya Pradesh",city:"Jabalpur",website:"https://www.iiitdmj.ac.in",established:2005,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Information Technology Kancheepuram",displayName:"IIIT Kancheepuram",institutionType:"IIIT",institutionFamily:"Engineering",state:"Tamil Nadu",city:"Kancheepuram",website:"https://www.iiitdm.ac.in",established:2007,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Information Technology Design and Manufacturing Kurnool",displayName:"IIITDM Kurnool",institutionType:"IIIT",institutionFamily:"Engineering",state:"Andhra Pradesh",city:"Kurnool",website:"https://www.iiitk.ac.in",established:2015,searchBoost:1.0,coreTier:1},
  {canonicalName:"Indian Institute of Information Technology Sri City",displayName:"IIIT Sri City",institutionType:"IIIT",institutionFamily:"Engineering",state:"Andhra Pradesh",city:"Sri City",website:"https://www.iiits.ac.in",established:2013,searchBoost:1.0,coreTier:1},
  {canonicalName:"Indian Institute of Information Technology Vadodara",displayName:"IIIT Vadodara",institutionType:"IIIT",institutionFamily:"Engineering",state:"Gujarat",city:"Vadodara",website:"https://www.iiitvadodara.ac.in",established:2013,searchBoost:1.0,coreTier:1},
  {canonicalName:"Indian Institute of Information Technology Lucknow",displayName:"IIIT Lucknow",institutionType:"IIIT",institutionFamily:"Engineering",state:"Uttar Pradesh",city:"Lucknow",website:"https://www.iiitl.ac.in",established:2015,searchBoost:1.0,coreTier:1},
  {canonicalName:"Indian Institute of Information Technology Pune",displayName:"IIIT Pune",institutionType:"IIIT",institutionFamily:"Engineering",state:"Maharashtra",city:"Pune",website:"https://www.iiitp.ac.in",established:2016,searchBoost:1.0,coreTier:1},

  // ── IISc + IISERs ─────────────────────────────────────────────────────────
  {canonicalName:"Indian Institute of Science",displayName:"IISc Bangalore",institutionType:"IISc",institutionFamily:"Science & Research",state:"Karnataka",city:"Bangalore",website:"https://www.iisc.ac.in",established:1909,searchBoost:1.6,coreTier:1},
  {canonicalName:"Indian Institute of Science Education and Research Pune",displayName:"IISER Pune",institutionType:"IISER",institutionFamily:"Science & Research",state:"Maharashtra",city:"Pune",website:"https://www.iiserpune.ac.in",established:2006,searchBoost:1.3,coreTier:1},
  {canonicalName:"Indian Institute of Science Education and Research Kolkata",displayName:"IISER Kolkata",institutionType:"IISER",institutionFamily:"Science & Research",state:"West Bengal",city:"Kolkata",website:"https://www.iiserkol.ac.in",established:2006,searchBoost:1.3,coreTier:1},
  {canonicalName:"Indian Institute of Science Education and Research Mohali",displayName:"IISER Mohali",institutionType:"IISER",institutionFamily:"Science & Research",state:"Punjab",city:"Mohali",website:"https://www.iisermohali.ac.in",established:2007,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Science Education and Research Bhopal",displayName:"IISER Bhopal",institutionType:"IISER",institutionFamily:"Science & Research",state:"Madhya Pradesh",city:"Bhopal",website:"https://www.iiserbhopal.ac.in",established:2008,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Science Education and Research Thiruvananthapuram",displayName:"IISER TVM",institutionType:"IISER",institutionFamily:"Science & Research",state:"Kerala",city:"Thiruvananthapuram",website:"https://www.iisertvm.ac.in",established:2008,searchBoost:1.2,coreTier:1},
  {canonicalName:"Indian Institute of Science Education and Research Tirupati",displayName:"IISER Tirupati",institutionType:"IISER",institutionFamily:"Science & Research",state:"Andhra Pradesh",city:"Tirupati",website:"https://www.iisertirupati.ac.in",established:2015,searchBoost:1.1,coreTier:1},
  {canonicalName:"Indian Institute of Science Education and Research Berhampur",displayName:"IISER Berhampur",institutionType:"IISER",institutionFamily:"Science & Research",state:"Odisha",city:"Berhampur",website:"https://www.iiserbpr.ac.in",established:2016,searchBoost:1.0,coreTier:1},

  // ── AIIMS ─────────────────────────────────────────────────────────────────
  {canonicalName:"All India Institute of Medical Sciences Delhi",displayName:"AIIMS Delhi",institutionType:"AIIMS",institutionFamily:"Medical",state:"Delhi",city:"New Delhi",website:"https://www.aiims.edu",established:1956,searchBoost:1.6,coreTier:1},
  {canonicalName:"All India Institute of Medical Sciences Jodhpur",displayName:"AIIMS Jodhpur",institutionType:"AIIMS",institutionFamily:"Medical",state:"Rajasthan",city:"Jodhpur",website:"https://www.aiimsjodhpur.edu.in",established:2012,searchBoost:1.4,coreTier:1},
  {canonicalName:"All India Institute of Medical Sciences Rishikesh",displayName:"AIIMS Rishikesh",institutionType:"AIIMS",institutionFamily:"Medical",state:"Uttarakhand",city:"Rishikesh",website:"https://www.aiimsrishikesh.edu.in",established:2012,searchBoost:1.4,coreTier:1},
  {canonicalName:"All India Institute of Medical Sciences Bhopal",displayName:"AIIMS Bhopal",institutionType:"AIIMS",institutionFamily:"Medical",state:"Madhya Pradesh",city:"Bhopal",website:"https://www.aiimsbhopal.edu.in",established:2012,searchBoost:1.4,coreTier:1},
  {canonicalName:"All India Institute of Medical Sciences Raipur",displayName:"AIIMS Raipur",institutionType:"AIIMS",institutionFamily:"Medical",state:"Chhattisgarh",city:"Raipur",website:"https://www.aiimsraipur.edu.in",established:2012,searchBoost:1.4,coreTier:1},
  {canonicalName:"All India Institute of Medical Sciences Patna",displayName:"AIIMS Patna",institutionType:"AIIMS",institutionFamily:"Medical",state:"Bihar",city:"Patna",website:"https://www.aiimspatna.org",established:2012,searchBoost:1.4,coreTier:1},
  {canonicalName:"All India Institute of Medical Sciences Bhubaneswar",displayName:"AIIMS Bhubaneswar",institutionType:"AIIMS",institutionFamily:"Medical",state:"Odisha",city:"Bhubaneswar",website:"https://www.aiimsbhubaneswar.nic.in",established:2012,searchBoost:1.4,coreTier:1},
  {canonicalName:"All India Institute of Medical Sciences Nagpur",displayName:"AIIMS Nagpur",institutionType:"AIIMS",institutionFamily:"Medical",state:"Maharashtra",city:"Nagpur",website:"https://www.aiimsnagpur.edu.in",established:2018,searchBoost:1.3,coreTier:1},
  {canonicalName:"All India Institute of Medical Sciences Mangalagiri",displayName:"AIIMS Mangalagiri",institutionType:"AIIMS",institutionFamily:"Medical",state:"Andhra Pradesh",city:"Mangalagiri",website:"https://www.aiimsmangalagiri.edu.in",established:2018,searchBoost:1.3,coreTier:1},
  {canonicalName:"All India Institute of Medical Sciences Gorakhpur",displayName:"AIIMS Gorakhpur",institutionType:"AIIMS",institutionFamily:"Medical",state:"Uttar Pradesh",city:"Gorakhpur",website:"https://www.aiimsgorakhpur.edu.in",established:2019,searchBoost:1.2,coreTier:1},

  // ── Top Medical Institutions ───────────────────────────────────────────────
  {canonicalName:"Jawaharlal Institute of Postgraduate Medical Education and Research",displayName:"JIPMER Puducherry",institutionType:"Medical",institutionFamily:"Medical",state:"Puducherry",city:"Puducherry",website:"https://www.jipmer.edu.in",established:1823,searchBoost:1.4,coreTier:1},
  {canonicalName:"Christian Medical College Vellore",displayName:"CMC Vellore",institutionType:"Medical",institutionFamily:"Medical",state:"Tamil Nadu",city:"Vellore",website:"https://www.cmch-vellore.edu",established:1900,searchBoost:1.4,coreTier:1},
  {canonicalName:"Postgraduate Institute of Medical Education and Research",displayName:"PGIMER Chandigarh",institutionType:"Medical",institutionFamily:"Medical",state:"Chandigarh",city:"Chandigarh",website:"https://www.pgimer.edu.in",established:1962,searchBoost:1.4,coreTier:1},
  {canonicalName:"Armed Forces Medical College",displayName:"AFMC Pune",institutionType:"Medical",institutionFamily:"Medical",state:"Maharashtra",city:"Pune",website:"https://www.afmc.nic.in",established:1948,searchBoost:1.3,coreTier:1},

  // ── Top Private Engineering ────────────────────────────────────────────────
  {canonicalName:"BITS Pilani",displayName:"BITS Pilani",institutionType:"Deemed",institutionFamily:"Engineering",state:"Rajasthan",city:"Pilani",website:"https://www.bits-pilani.ac.in",established:1964,searchBoost:1.4,coreTier:1},
  {canonicalName:"BITS Pilani Goa",displayName:"BITS Goa",institutionType:"Deemed",institutionFamily:"Engineering",state:"Goa",city:"Goa",website:"https://www.bits-pilani.ac.in/goa",established:2004,searchBoost:1.3,coreTier:1},
  {canonicalName:"BITS Pilani Hyderabad",displayName:"BITS Hyderabad",institutionType:"Deemed",institutionFamily:"Engineering",state:"Telangana",city:"Hyderabad",website:"https://www.bits-pilani.ac.in/hyderabad",established:2008,searchBoost:1.3,coreTier:1},
  {canonicalName:"Vellore Institute of Technology",displayName:"VIT Vellore",institutionType:"Deemed",institutionFamily:"Engineering",state:"Tamil Nadu",city:"Vellore",website:"https://www.vit.ac.in",established:1984,searchBoost:1.3,coreTier:1},
  {canonicalName:"Manipal Institute of Technology",displayName:"MIT Manipal",institutionType:"Deemed",institutionFamily:"Engineering",state:"Karnataka",city:"Manipal",website:"https://manipal.edu/mit.html",established:1957,searchBoost:1.2,coreTier:1},
  {canonicalName:"Thapar Institute of Engineering and Technology",displayName:"Thapar University",institutionType:"Deemed",institutionFamily:"Engineering",state:"Punjab",city:"Patiala",website:"https://www.thapar.edu",established:1956,searchBoost:1.3,coreTier:1},
  {canonicalName:"SRM Institute of Science and Technology",displayName:"SRM University",institutionType:"Deemed",institutionFamily:"Engineering",state:"Tamil Nadu",city:"Chennai",website:"https://www.srmist.edu.in",established:1985,searchBoost:1.2,coreTier:1},
  {canonicalName:"Amrita Vishwa Vidyapeetham",displayName:"Amrita University",institutionType:"Deemed",institutionFamily:"Engineering",state:"Tamil Nadu",city:"Coimbatore",website:"https://www.amrita.edu",established:2003,searchBoost:1.2,coreTier:1},
  {canonicalName:"Nirma University",displayName:"Nirma University",institutionType:"Deemed",institutionFamily:"Engineering",state:"Gujarat",city:"Ahmedabad",website:"https://www.nirmauni.ac.in",established:1994,searchBoost:1.2,coreTier:1},
  {canonicalName:"Dhirubhai Ambani Institute of Information and Communication Technology",displayName:"DAIICT Gandhinagar",institutionType:"Deemed",institutionFamily:"Engineering",state:"Gujarat",city:"Gandhinagar",website:"https://www.daiict.ac.in",established:2001,searchBoost:1.2,coreTier:1},

  // ── Central Universities ───────────────────────────────────────────────────
  {canonicalName:"University of Delhi",displayName:"Delhi University",institutionType:"Central University",institutionFamily:"Multidisciplinary",state:"Delhi",city:"New Delhi",website:"https://www.du.ac.in",established:1922,searchBoost:1.4,coreTier:1},
  {canonicalName:"Jawaharlal Nehru University",displayName:"JNU Delhi",institutionType:"Central University",institutionFamily:"Social Sciences",state:"Delhi",city:"New Delhi",website:"https://www.jnu.ac.in",established:1969,searchBoost:1.4,coreTier:1},
  {canonicalName:"Banaras Hindu University",displayName:"BHU Varanasi",institutionType:"Central University",institutionFamily:"Multidisciplinary",state:"Uttar Pradesh",city:"Varanasi",website:"https://www.bhu.ac.in",established:1916,searchBoost:1.3,coreTier:1},
  {canonicalName:"Hyderabad University",displayName:"University of Hyderabad",institutionType:"Central University",institutionFamily:"Social Sciences",state:"Telangana",city:"Hyderabad",website:"https://uohyd.ac.in",established:1974,searchBoost:1.3,coreTier:1},
  {canonicalName:"Jamia Millia Islamia",displayName:"Jamia Millia Islamia",institutionType:"Central University",institutionFamily:"Multidisciplinary",state:"Delhi",city:"New Delhi",website:"https://www.jmi.ac.in",established:1920,searchBoost:1.2,coreTier:1},
  {canonicalName:"Aligarh Muslim University",displayName:"AMU Aligarh",institutionType:"Central University",institutionFamily:"Multidisciplinary",state:"Uttar Pradesh",city:"Aligarh",website:"https://www.amu.ac.in",established:1875,searchBoost:1.2,coreTier:1},
  {canonicalName:"Jadavpur University",displayName:"Jadavpur University",institutionType:"State University",institutionFamily:"Engineering",state:"West Bengal",city:"Kolkata",website:"https://jadavpuruniversity.in",established:1955,searchBoost:1.3,coreTier:1},
  {canonicalName:"Delhi Technological University",displayName:"DTU Delhi",institutionType:"State University",institutionFamily:"Engineering",state:"Delhi",city:"New Delhi",website:"https://www.dtu.ac.in",established:1941,searchBoost:1.3,coreTier:1},
  {canonicalName:"College of Engineering Pune",displayName:"COEP Pune",institutionType:"State University",institutionFamily:"Engineering",state:"Maharashtra",city:"Pune",website:"https://www.coep.org.in",established:1854,searchBoost:1.2,coreTier:1},

  // ── Top Business Schools ───────────────────────────────────────────────────
  {canonicalName:"FMS Delhi",displayName:"FMS Delhi",institutionType:"University",institutionFamily:"Management",state:"Delhi",city:"New Delhi",website:"https://fms.edu",established:1954,searchBoost:1.5,coreTier:1},
  {canonicalName:"XLRI Jamshedpur",displayName:"XLRI Jamshedpur",institutionType:"Private",institutionFamily:"Management",state:"Jharkhand",city:"Jamshedpur",website:"https://www.xlri.ac.in",established:1949,searchBoost:1.5,coreTier:1},
  {canonicalName:"SPJIMR Mumbai",displayName:"SPJIMR Mumbai",institutionType:"Private",institutionFamily:"Management",state:"Maharashtra",city:"Mumbai",website:"https://www.spjimr.org",established:1981,searchBoost:1.4,coreTier:1},
  {canonicalName:"MDI Gurgaon",displayName:"MDI Gurgaon",institutionType:"Private",institutionFamily:"Management",state:"Haryana",city:"Gurugram",website:"https://www.mdi.ac.in",established:1973,searchBoost:1.4,coreTier:1},
  {canonicalName:"TISS Mumbai",displayName:"TISS Mumbai",institutionType:"Deemed",institutionFamily:"Social Sciences",state:"Maharashtra",city:"Mumbai",website:"https://www.tiss.edu",established:1936,searchBoost:1.3,coreTier:1},
  {canonicalName:"Symbiosis Institute of Business Management",displayName:"SIBM Pune",institutionType:"Deemed",institutionFamily:"Management",state:"Maharashtra",city:"Pune",website:"https://www.sibmpune.edu.in",established:1978,searchBoost:1.2,coreTier:1},
  {canonicalName:"Institute of Management Technology Ghaziabad",displayName:"IMT Ghaziabad",institutionType:"Private",institutionFamily:"Management",state:"Uttar Pradesh",city:"Ghaziabad",website:"https://www.imt.edu",established:1980,searchBoost:1.2,coreTier:1},
  {canonicalName:"Great Lakes Institute of Management",displayName:"Great Lakes Chennai",institutionType:"Private",institutionFamily:"Management",state:"Tamil Nadu",city:"Chennai",website:"https://www.greatlakes.edu.in",established:2004,searchBoost:1.1,coreTier:1},

  // ── Top NLUs ──────────────────────────────────────────────────────────────
  {canonicalName:"National Law School of India University",displayName:"NLSIU Bangalore",institutionType:"NLU",institutionFamily:"Law",state:"Karnataka",city:"Bangalore",website:"https://www.nls.ac.in",established:1987,searchBoost:1.4,coreTier:1},
  {canonicalName:"NALSAR University of Law",displayName:"NALSAR Hyderabad",institutionType:"NLU",institutionFamily:"Law",state:"Telangana",city:"Hyderabad",website:"https://nalsar.ac.in",established:1998,searchBoost:1.3,coreTier:1},
  {canonicalName:"National Law University Delhi",displayName:"NLU Delhi",institutionType:"NLU",institutionFamily:"Law",state:"Delhi",city:"New Delhi",website:"https://www.nludelhi.ac.in",established:2008,searchBoost:1.3,coreTier:1},
  {canonicalName:"West Bengal National University of Juridical Sciences",displayName:"NUJS Kolkata",institutionType:"NLU",institutionFamily:"Law",state:"West Bengal",city:"Kolkata",website:"https://www.nujs.edu",established:1999,searchBoost:1.3,coreTier:1},
  {canonicalName:"National Law Institute University Bhopal",displayName:"NLIU Bhopal",institutionType:"NLU",institutionFamily:"Law",state:"Madhya Pradesh",city:"Bhopal",website:"https://www.nliu.ac.in",established:1997,searchBoost:1.2,coreTier:1},

  // ── Design / Architecture ──────────────────────────────────────────────────
  {canonicalName:"National Institute of Design Ahmedabad",displayName:"NID Ahmedabad",institutionType:"Design",institutionFamily:"Design",state:"Gujarat",city:"Ahmedabad",website:"https://www.nid.edu",established:1961,searchBoost:1.3,coreTier:1},
  {canonicalName:"National Institute of Fashion Technology Delhi",displayName:"NIFT Delhi",institutionType:"Design",institutionFamily:"Design",state:"Delhi",city:"New Delhi",website:"https://www.nift.ac.in",established:1986,searchBoost:1.2,coreTier:1},
  {canonicalName:"School of Planning and Architecture Delhi",displayName:"SPA Delhi",institutionType:"Government",institutionFamily:"Architecture",state:"Delhi",city:"New Delhi",website:"https://www.spa.ac.in",established:1955,searchBoost:1.2,coreTier:1},

  // ── Agriculture / Pharmacy ─────────────────────────────────────────────────
  {canonicalName:"Indian Agricultural Research Institute",displayName:"IARI New Delhi",institutionType:"Government",institutionFamily:"Agriculture",state:"Delhi",city:"New Delhi",website:"https://www.iari.res.in",established:1905,searchBoost:1.2,coreTier:1},
  {canonicalName:"Manipal College of Pharmaceutical Sciences",displayName:"MCOPS Manipal",institutionType:"Deemed",institutionFamily:"Pharmacy",state:"Karnataka",city:"Manipal",website:"https://manipal.edu/mcops.html",established:1963,searchBoost:1.1,coreTier:1},
];

const lines = institutes.map(i => JSON.stringify(i));
fs.writeFileSync(OUT, lines.join('\n') + '\n');
console.log(`✅ Written ${institutes.length} core institutes to ${OUT}`);
